#!/usr/bin/env bash

#
#  SPDX-License-Identifier: BSD-3-Clause
#  Copyright (C) 2025 Huawei Technologies
#  All rights reserved.
#

curdir=$(dirname $(readlink -f "${BASH_SOURCE[0]}"))
rootdir=$(readlink -f $curdir/../../..)
source "$rootdir/test/ocf/common.sh"

# caches only:

start_spdk
create_caches
start_caches
__check_caches_attached
detach_caches
__check_caches_detached
stop_spdk

start_spdk
create_caches
start_caches
__check_caches_attached
detach_caches
__check_caches_detached
stop_caches
__check_caches_empty
stop_spdk

start_spdk
create_caches
start_caches
__check_caches_attached
detach_caches
__check_caches_detached
attach_caches
__check_caches_attached
stop_spdk

start_spdk
create_caches
start_caches
__check_caches_attached
detach_caches
__check_caches_detached
attach_caches
__check_caches_attached
stop_caches
__check_caches_empty
stop_spdk

# add cores before detaching caches:

start_spdk
create_caches
create_cores
start_caches
add_cores
__check_caches_attached
__check_cores_attached
detach_caches
__check_caches_detached
__check_cores_attached
stop_spdk

start_spdk
create_caches
create_cores
start_caches
add_cores
__check_caches_attached
__check_cores_attached
detach_caches
__check_caches_detached
__check_cores_attached
stop_caches
__check_caches_empty
stop_spdk

start_spdk
create_caches
create_cores
start_caches
add_cores
__check_caches_attached
__check_cores_attached
detach_caches
__check_caches_detached
__check_cores_attached
attach_caches
__check_caches_attached
__check_cores_attached
stop_spdk

start_spdk
create_caches
create_cores
start_caches
add_cores
__check_caches_attached
__check_cores_attached
detach_caches
__check_caches_detached
__check_cores_attached
attach_caches
__check_caches_attached
__check_cores_attached
stop_caches
__check_caches_empty
stop_spdk

# add cores after detaching caches:

start_spdk
create_caches
create_cores
start_caches
__check_caches_attached
detach_caches
__check_caches_detached
add_cores
__check_caches_detached
__check_cores_waitlist_attached
stop_spdk

start_spdk
create_caches
create_cores
start_caches
__check_caches_attached
detach_caches
__check_caches_detached
add_cores
__check_caches_detached
__check_cores_waitlist_attached
stop_caches
__check_caches_empty
stop_spdk

start_spdk
create_caches
create_cores
start_caches
__check_caches_attached
detach_caches
__check_caches_detached
add_cores
__check_caches_detached
__check_cores_waitlist_attached
attach_caches
__check_caches_attached
__check_cores_attached
__check_cores_waitlist_empty
stop_spdk

start_spdk
create_caches
create_cores
start_caches
__check_caches_attached
detach_caches
__check_caches_detached
add_cores
__check_caches_detached
__check_cores_waitlist_attached
attach_caches
__check_caches_attached
__check_cores_attached
__check_cores_waitlist_empty
stop_caches
__check_caches_empty
stop_spdk

# add cores before and remove after detaching caches:

start_spdk
create_caches
create_cores
start_caches
add_cores
__check_caches_attached
__check_cores_attached
detach_caches
__check_caches_detached
__check_cores_attached
remove_cores
__check_caches_detached
__check_cores_empty
stop_spdk

start_spdk
create_caches
create_cores
start_caches
add_cores
__check_caches_attached
__check_cores_attached
detach_caches
__check_caches_detached
__check_cores_attached
remove_cores
__check_caches_detached
__check_cores_empty
stop_caches
__check_caches_empty
stop_spdk

start_spdk
create_caches
create_cores
start_caches
add_cores
__check_caches_attached
__check_cores_attached
detach_caches
__check_caches_detached
__check_cores_attached
remove_cores
__check_caches_detached
__check_cores_empty
attach_caches
__check_caches_attached
__check_cores_empty
stop_spdk

start_spdk
create_caches
create_cores
start_caches
add_cores
__check_caches_attached
__check_cores_attached
detach_caches
__check_caches_detached
__check_cores_attached
remove_cores
__check_caches_detached
__check_cores_empty
attach_caches
__check_caches_attached
__check_cores_empty
stop_caches
__check_caches_empty
stop_spdk

# add cores after detaching caches and remove (before/after/without) attaching:

start_spdk
create_caches
create_cores
start_caches
__check_caches_attached
detach_caches
__check_caches_detached
add_cores
__check_caches_detached
__check_cores_empty
__check_cores_waitlist_attached
remove_cores
__check_caches_detached
__check_cores_empty
__check_cores_waitlist_empty
stop_spdk

start_spdk
create_caches
create_cores
start_caches
__check_caches_attached
detach_caches
__check_caches_detached
add_cores
__check_caches_detached
__check_cores_empty
__check_cores_waitlist_attached
remove_cores
__check_caches_detached
__check_cores_empty
__check_cores_waitlist_empty
stop_caches
__check_caches_empty
stop_spdk

start_spdk
create_caches
create_cores
start_caches
__check_caches_attached
detach_caches
__check_caches_detached
add_cores
__check_caches_detached
__check_cores_waitlist_attached
remove_cores
__check_caches_detached
__check_cores_waitlist_empty
attach_caches
__check_caches_attached
__check_cores_empty
__check_cores_waitlist_empty
stop_spdk

start_spdk
create_caches
create_cores
start_caches
__check_caches_attached
detach_caches
__check_caches_detached
add_cores
__check_caches_detached
__check_cores_waitlist_attached
remove_cores
__check_caches_detached
__check_cores_waitlist_empty
attach_caches
__check_caches_attached
__check_cores_empty
__check_cores_waitlist_empty
stop_caches
__check_caches_empty
stop_spdk

start_spdk
create_caches
create_cores
start_caches
__check_caches_attached
detach_caches
__check_caches_detached
add_cores
__check_caches_detached
__check_cores_empty
__check_cores_waitlist_attached
attach_caches
__check_caches_attached
__check_cores_attached
__check_cores_waitlist_empty
remove_cores
__check_caches_attached
__check_cores_empty
__check_cores_waitlist_empty
stop_spdk

start_spdk
create_caches
create_cores
start_caches
__check_caches_attached
detach_caches
__check_caches_detached
add_cores
__check_caches_detached
__check_cores_empty
__check_cores_waitlist_attached
attach_caches
__check_caches_attached
__check_cores_attached
__check_cores_waitlist_empty
remove_cores
__check_caches_attached
__check_cores_empty
__check_cores_waitlist_empty
stop_caches
__check_caches_empty
stop_spdk
