#!/usr/bin/env bash

#
#  SPDX-License-Identifier: BSD-3-Clause
#  Copyright (C) 2025 Huawei Technologies
#  All rights reserved.
#

curdir=$(dirname $(readlink -f "${BASH_SOURCE[0]}"))
rootdir=$(readlink -f $curdir/../../../..)
source "$rootdir/test/ocf/common.sh"

# examine partial configuration (not all devices present):

start_spdk
start_caches
__check_caches_detached
create_caches
__check_caches_attached
stop_spdk

start_spdk
start_caches
__check_caches_detached
create_caches
__check_caches_attached
stop_caches
__check_caches_empty
stop_spdk

start_spdk
start_caches
add_cores
__check_caches_detached
__check_cores_waitlist_detached
create_caches
__check_caches_attached
__check_cores_waitlist_detached
stop_spdk

start_spdk
start_caches
add_cores
__check_caches_detached
__check_cores_waitlist_detached
create_caches
__check_caches_attached
__check_cores_waitlist_detached
stop_caches
__check_caches_empty
__check_cores_waitlist_detached
stop_spdk

start_spdk
add_cores
__check_cores_waitlist_detached
create_cores
__check_cores_waitlist_attached
stop_spdk

start_spdk
start_caches
add_cores
__check_caches_detached
__check_cores_empty
__check_cores_waitlist_detached
create_cores
__check_cores_empty
__check_cores_waitlist_attached
stop_spdk

start_spdk
start_caches
add_cores
__check_caches_detached
__check_cores_empty
__check_cores_waitlist_detached
create_cores
__check_cores_empty
__check_cores_waitlist_attached
stop_caches
__check_caches_empty
__check_cores_waitlist_attached
stop_spdk

start_spdk
add_cores
__check_cores_waitlist_detached
create_cores
__check_cores_waitlist_attached
start_caches
__check_caches_detached
__check_cores_empty
__check_cores_waitlist_attached
stop_spdk

start_spdk
add_cores
__check_cores_waitlist_detached
create_cores
__check_cores_waitlist_attached
start_caches
__check_caches_detached
__check_cores_empty
__check_cores_waitlist_attached
stop_caches
__check_caches_empty
__check_cores_waitlist_attached
stop_spdk

start_spdk
add_cores
__check_cores_waitlist_detached
create_cores
__check_cores_waitlist_attached
start_caches
__check_caches_detached
__check_cores_empty
__check_cores_waitlist_attached
remove_cores
__check_cores_waitlist_empty
stop_spdk

start_spdk
add_cores
__check_cores_waitlist_detached
create_cores
__check_cores_waitlist_attached
start_caches
__check_caches_detached
__check_cores_empty
__check_cores_waitlist_attached
remove_cores
__check_cores_waitlist_empty
stop_caches
__check_caches_empty
stop_spdk

start_spdk
add_cores
start_caches
__check_caches_detached
__check_cores_empty
__check_cores_waitlist_detached
create_cores
__check_cores_waitlist_attached
stop_spdk

start_spdk
add_cores
start_caches
__check_caches_detached
__check_cores_empty
__check_cores_waitlist_detached
create_cores
__check_cores_waitlist_attached
stop_caches
__check_caches_empty
__check_cores_waitlist_attached
stop_spdk

# examine full configuration with inversing order:

start_spdk
start_caches
add_cores
__check_caches_detached
__check_cores_empty
__check_cores_waitlist_detached
create_caches
__check_caches_attached
__check_cores_empty
create_cores
__check_cores_attached
__check_cores_waitlist_empty
stop_spdk

start_spdk
start_caches
add_cores
__check_caches_detached
__check_cores_empty
__check_cores_waitlist_detached
create_caches
__check_caches_attached
__check_cores_empty
create_cores
__check_cores_attached
__check_cores_waitlist_empty
stop_caches
__check_caches_empty
__check_cores_waitlist_empty
stop_spdk

start_spdk
start_caches
add_cores
__check_caches_detached
__check_cores_empty
__check_cores_waitlist_detached
create_cores
__check_cores_waitlist_attached
create_caches
__check_caches_attached
__check_cores_attached
__check_cores_waitlist_empty
stop_spdk

start_spdk
start_caches
add_cores
__check_caches_detached
__check_cores_empty
__check_cores_waitlist_detached
create_cores
__check_cores_waitlist_attached
create_caches
__check_caches_attached
__check_cores_attached
__check_cores_waitlist_empty
stop_caches
__check_caches_empty
stop_spdk

start_spdk
add_cores
start_caches
__check_caches_detached
__check_cores_empty
__check_cores_waitlist_detached
create_caches
__check_caches_attached
__check_cores_empty
create_cores
__check_cores_attached
__check_cores_waitlist_empty
stop_spdk

start_spdk
add_cores
start_caches
__check_caches_detached
__check_cores_empty
__check_cores_waitlist_detached
create_caches
__check_caches_attached
__check_cores_empty
create_cores
__check_cores_attached
__check_cores_waitlist_empty
stop_caches
__check_caches_empty
stop_spdk

start_spdk
add_cores
start_caches
__check_caches_detached
__check_cores_empty
__check_cores_waitlist_detached
create_cores
__check_cores_waitlist_attached
create_caches
__check_caches_attached
__check_cores_attached
__check_cores_waitlist_empty
stop_spdk

start_spdk
add_cores
start_caches
__check_caches_detached
__check_cores_empty
__check_cores_waitlist_detached
create_cores
__check_cores_waitlist_attached
create_caches
__check_caches_attached
__check_cores_attached
__check_cores_waitlist_empty
stop_caches
__check_caches_empty
stop_spdk

# examine found core (not yet added or hotremoved) on detached cache:

start_spdk
create_caches
start_caches
add_cores
__check_caches_attached
__check_cores_waitlist_detached
detach_caches
__check_caches_detached
create_cores
__check_caches_detached
__check_cores_waitlist_attached
attach_caches
__check_caches_attached
__check_cores_attached
__check_cores_waitlist_empty
stop_spdk

start_spdk
create_caches
start_caches
add_cores
__check_caches_attached
__check_cores_waitlist_detached
detach_caches
__check_caches_detached
create_cores
__check_caches_detached
__check_cores_waitlist_attached
attach_caches
__check_caches_attached
__check_cores_attached
__check_cores_waitlist_empty
stop_caches
__check_caches_empty
stop_spdk

start_spdk
create_caches
create_cores
start_caches
add_cores
__check_caches_attached
__check_cores_attached
detach_caches
__check_caches_detached
destroy_cores
__check_cores_detached
create_cores
__check_caches_detached
__check_cores_attached
attach_caches
__check_caches_attached
__check_cores_attached
stop_spdk

start_spdk
create_caches
create_cores
start_caches
add_cores
__check_caches_attached
__check_cores_attached
detach_caches
__check_caches_detached
destroy_cores
__check_cores_detached
create_cores
__check_caches_detached
__check_cores_attached
attach_caches
__check_caches_attached
__check_cores_attached
stop_caches
__check_caches_empty
stop_spdk
